apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-replicaset
  namespace: db
  labels:
    app: mysql

spec:
  replicas: 2  # Modify the "replicas" value as per your requirement
  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql

    spec:
      containers:
        - name: mysql-container
          image: 025394766800.dkr.ecr.us-east-1.amazonaws.com/clo835-ecr:V1-mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpassword"
          ports:
            - containerPort: 3306
      imagePullSecrets:
        - name: myecrsecret
