apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: DB
  labels:
    app: mysql

spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql

    spec:
      containers:
        - name: mysql-container
          image:
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpassword"
          ports:
            - containerPort: 3306
