apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: db
  labels:
    app: mysql
spec:
  containers:
    - name: mysql-container
      image: 025394766800.dkr.ecr.us-east-1.amazonaws.com/clo835-ecr:mysql-V2
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword"
  imagePullSecrets:
    - name: myecrsecret
