apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: DB
  labels:
    app: mysql
spec:
  containers:
    - name: mysql-container
      image:
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword"
