apiVersion: v1
kind: Pod
metadata:
  name: web-app
  labels:
    app: employees
spec:
  containers:
  - name: web-app
    image: 025394766800.dkr.ecr.us-east-1.amazonaws.com/clo835-ecr:latest-app
    ports:
    - containerPort: 8080
