apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  namespace: app
  labels:
    app: employees

spec:
  containers:
  - name: webapp-container
    image: 025394766800.dkr.ecr.us-east-1.amazonaws.com/clo835-ecr:V2-app
    ports:
    - containerPort: 8080
    env:
    - name: DBHOST
      value: "mysql-service.DB.svc.cluster.local"
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: "root"
    - name: DBPWD
      value: "rootpassword"
    
  
