apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-replicaset
  labels:
    app: employees

spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees

  template:
    metadata:
      labels:
        app: employees

    spec:
      containers:
        - name: webapp-container
          image: 025394766800.dkr.ecr.us-east-1.amazonaws.com/clo835-ecr:app-V2
          env:
            - name: DBUSER
              value: "root"
            - name: DBPWD
              value: "rootpassword"
            - name: DBPORT
              value: "3306"
            - name: DBHOST
              value: "mysql-service.db.svc.cluster.local"
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: myecrsecret
