apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: app
  labels:
    app: employees
spec:
  selector:
      app: employees
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000