name: Deploy to ECR
# updated ECR Repo week3-1
on:
  workflow_dispatch:
  #push:
   # branches:
     # - main

jobs:
  build:
    name: Build and Push Images
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: us-east-1

      - name: Build and Push App image V1
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: clo835-ecr
          IMAGE_TAG: latest
        run: |
          ls -ltra
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:app-$IMAGE_TAG -f Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:app-$IMAGE_TAG

      - name: Build and Push SQL image V1
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: clo835-ecr
          IMAGE_TAG: latest
        run: |
          ls -ltra
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:mysql-$IMAGE_TAG -f Dockerfile_mysql .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:mysql-$IMAGE_TAG

      - name: Build and Push App image V2
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: clo835-ecr
          IMAGE_TAG: V2
        run: |
          ls -ltra
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:app-$IMAGE_TAG -f Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:app-$IMAGE_TAG

      - name: Build and Push SQL image V2
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: clo835-ecr
          IMAGE_TAG: V2
        run: |
          ls -ltra
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:mysql-$IMAGE_TAG -f Dockerfile_mysql .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:mysql-$IMAGE_TAG
